### PR TITLE
fix #60

### LINKED ISSUE #60: Open Web App support
In this way we can install it on Android and Firefox OS without use the bookmarks

### PR DESCRIPTION
**Pull request by Mte90**
index
index2

This pr add a link Install in the menu that is hide when the app is installed or is not compatible with open web app.
Now that button enable the support to install the app when you go on the site and work also on Firefox and Firefox for android.

### CODE REVIEW

**Comment by mmmavis** [comment]
thank you @Mte90 ! 

let me see if I can find someone else to review this PR as I don't have experience with Open Web App :grimacing:

**Comment by Pomax** [comment]
hm, running this on desktop firefox, the installation works but starting up the app throws "Cannot GET /mozfest-schedule-app/index.html" so I suspect the manifest still needs a field that indicates what counts as "root" for the app.

**Comment by Mte90** [comment]
Can you try to replace in the manifest.webapp launchpath with absolute path
of the site? I've tried locally with a Web server and worked.

**Comment by ioana-chiorean** [comment]
Wrong reference - don't mind that

**Comment by Mte90** [comment]
[**@Pomax**](https://github.com/Pomax) commented on [5 nov 2015, 18:23 CET](https://github.com/mozilla/mozfest-schedule-app/pull/64#issuecomment-154128284 "2015-11-05T17:23:04Z - Replied by Github Comment Enhancer"):
> hm, running this on desktop firefox, the installation works but starting up the app throws "Cannot GET /mozfest-schedule-app/index.html" so I suspect the manifest still needs a field that indicates what counts as "root" for the app, or the `launch` field is not quite right

any news?

**Comment by Pomax** [comment]
I tried updating the manifest, but after the initial install I cannot seem to get this to register as able to install anymore. Checking owa.js, the result of the `var checkIfInstalled = navigator.mozApps.getSelf();` call is
```
DOMRequest { readyState: "pending", error: null, onsuccess: null, onerror: null }
```
and binding the onsuccess and onerror doesn't, in itself, do anything.

**Comment by Mte90** [comment]
very strange i need to check but in my system works without problem.

**Comment by flamingspaz** [comment]
You'd probably need to change the manifest to use app.mozillafestival.org instead of the github link.

**Comment by Pomax** [comment]
that's what I did. The manifest I've tried with is this:
```
{
  "version": "1",
  "name": "MozFest Schedule",
  "launch_path": "https://app.mozillafestival.org/index.html",
  "description": "Mobile-oriented web app for displaying MozFest schedule data",
  "icons": {
    "16": "https://app.mozillafestival.org/img/logo16.png",
    "32": "https://app.mozillafestival.org/img/logo32.png",
    "48": "https://app.mozillafestival.org/img/logo48.png",
    "60": "https://app.mozillafestival.org/img/logo60.png",
    "64": "https://app.mozillafestival.org/img/logo64.png",
    "90": "https://app.mozillafestival.org/img/logo90.png",
    "120": "https://app.mozillafestival.org/img/logo120.png",
    "128": "https://app.mozillafestival.org/img/logo128.png"
  },
  "developer": {
    "name": "Mozilla",
    "url": "https://mozilla.github.io/mozfest-schedule-app/"
  },
  "installs_allowed_from": [
    "*"
  ],
  "default_locale": "en",
  "locales": {
   "en": {
      "name": "MozFest Schedule",
      "description": "Mobile-oriented web app for displaying MozFest schedule data"
    }
  }
} 
```

**Comment by Mte90** [comment]
with that url i get an invalid manifest, if i am not wrong that require not an absolute path but a relative path.
actually i am busy at mozfest to check that.

**Comment by Pomax** [comment]
so am I, this might have to wait until after.

**Comment by Mte90** [comment]
I've tested locally with an url http://localhost/mozfest-schedule-app/ work without problems so if that code is in the root of a project the launch_path will be `index.html`.

**Comment by Mte90** [comment]
if that pr is abandoned i close it

**Comment by Pomax** [comment]
we'll be revisiting this project soon as part of our 2016 project planning, so even though not much has happened between MozFest and Christmas/New Year break due to other projects having end-of-year precedence, it's good to keep this open. It's certainly still worth doing, there just isn't quite a roadmap yet for when we resume work on the schedule app (ideally of course, sooner than later!)

**Pull request closed without merging**
